import { PricingPlan } from "./pricingPlans.types";

export const pricingPlans: PricingPlan[] = [
  {
    id: "basic",
    name: "Basic Plan",
    price: 1500,
    billing: "/m",
    buttonText: "Get Started",
    features: [
      "10% Affiliate Commission",
      "20 Product Listings",
      "Basic Seller Dashboard",
      "Order Management",
      "Email Support",
      "Sales Performance Reports",
      "More Friendly Storefront",
    ],
  },
{
  id: "basic-plus",
  name: "Pro Plan",
  price: 3000,
  billing: "/m",
  buttonText: "Get Started",
  featured: true,
features: [
  "Everything in Starter",
  "15% commission on every successful sale",
  "Publish up to 30 products",
  "40 day subscription duration",
  "Higher earning potential",
  "Expand your product catalog",
  "Ideal for growing affiliate businesses",
  "Access to order management",
  "Real time earnings dashboard",
  "Withdrawal request support",
],
},
{
  id: "premium",
  name: "Elite Plan",
  price: 5000,
  billing: "/m",
  buttonText: "Get Started",
features: [
  "Everything in Pro",
  "30% commission on every successful sale",
  "Publish up to 50 products",
  "90 day subscription duration",
  "Highest commission available",
  "Maximum product visibility",
  "Built for high volume affiliates",
  "Priority product publishing capacity",
  "Longer uninterrupted selling period",
  "Maximize earnings across more products",
  "Scale your affiliate business faster",
  "Unlock the platform's highest available plan",
],
},
];