import { PricingPlan } from "./pricingPlans.types";

export const pricingPlans: PricingPlan[] = [
{
    id: "basic",
    name: "Basic Plan",
    price: 200,
    billing: "/m",
    buttonText: "Get Started",
    features: [
      "5% Affiliate Commission",
      "Publish up to 5 products",
      "10 day subscription duration",
      "Basic Seller Dashboard",
      "Order Management",
      "Email Support",
      "Sales Performance Reports",
      "More Friendly Storefront",
    ],
  },
{
    id: "regular",
    name: "Regular Plan",
    price: 350,
    billing: "/m",
    buttonText: "Get Started",
    featured: true,
    features: [
      "Everything in Starter",
      "10% commission on every successful sale",
      "Publish up to 10 products",
      "15 day subscription duration",
      "Higher earning potential",
      "Expand your product catalog",
      "Ideal for growing affiliate businesses",
      "Access to order management",
      "Real time earnings dashboard",
      "Withdrawal request support",
    ],
  },
{
    id: "pro",
    name: "Pro Plan",
    price: 500,
    billing: "/m",
    buttonText: "Get Started",
    features: [
      "Everything in Pro",
      "15% commission on every successful sale",
      "Publish up to 17 products",
      "20 day subscription duration",
      "Highest commission available",
      "Maximum product visibility",
      "Built for high volume affiliates",
      "Priority product publishing capacity",
      "Longer uninterrupted selling period",
      "Maximize earnings across more products",
      "Scale your affiliate business faster",
      "Unlock the platform's highest available plan",
    ],
  },
];