"use client";

export default function WalletLoadingSkeleton() {
  return (
    <div
      className="
        w-full
        overflow-hidden
        rounded-[var(--admin-card-radius)]
        border
        border-[var(--admin-card-border)]
        bg-[var(--admin-card-bg)]
        shadow-[var(--admin-card-shadow)]
      "
    >
      <div className="overflow-x-auto">
        <table
          className="
            w-full
            min-w-[960px]
            border-collapse
          "
        >
          <thead>
            <tr
              className="
                border-b
                border-[var(--admin-table-border)]
                bg-[var(--admin-table-header-bg)]
              "
            >
              {[
                "User",
                "Email",
                "Balance",
                "Status",
                "Actions",
              ].map((label) => (
                <th
                  key={label}
                  className="
                    px-3
                    py-2.5
                    text-left
                    text-[10px]
                    font-semibold
                    uppercase
                    tracking-[0.08em]
                    text-[var(--admin-table-header-text)]
                    sm:px-4
                    sm:py-3
                  "
                >
                  {label}
                </th>
              ))}
            </tr>
          </thead>

          <tbody>
            {Array.from({
              length: 8,
            }).map((_, row) => (
              <tr
                key={row}
                className="
                  border-b
                  border-[var(--admin-table-border)]
                "
              >
                <td
                  className="
                    px-3
                    py-3
                    sm:px-4
                    sm:py-3.5
                  "
                >
                  <div className="space-y-1.5">
                    <div
                      className="
                        h-3
                        w-32
                        animate-pulse
                        rounded
                        bg-[var(--admin-table-header-bg)]
                      "
                    />

                    <div
                      className="
                        h-2.5
                        w-20
                        animate-pulse
                        rounded
                        bg-[var(--admin-table-header-bg)]
                      "
                    />
                  </div>
                </td>

                <td
                  className="
                    px-3
                    py-3
                    sm:px-4
                    sm:py-3.5
                  "
                >
                  <div
                    className="
                      h-3
                      w-full
                      max-w-[180px]
                      animate-pulse
                      rounded
                      bg-[var(--admin-table-header-bg)]
                    "
                  />
                </td>

                <td
                  className="
                    px-3
                    py-3
                    sm:px-4
                    sm:py-3.5
                  "
                >
                  <div
                    className="
                      h-3
                      w-20
                      animate-pulse
                      rounded
                      bg-[var(--admin-table-header-bg)]
                    "
                  />
                </td>

                <td
                  className="
                    px-3
                    py-3
                    sm:px-4
                    sm:py-3.5
                  "
                >
                  <div
                    className="
                      h-5
                      w-16
                      animate-pulse
                      rounded-full
                      bg-[var(--admin-table-header-bg)]
                    "
                  />
                </td>

                <td
                  className="
                    px-3
                    py-3
                    text-right
                    sm:px-4
                    sm:py-3.5
                  "
                >
                  <div
                    className="
                      ml-auto
                      h-6
                      w-16
                      animate-pulse
                      rounded-md
                      bg-[var(--admin-table-header-bg)]
                    "
                  />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}